on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check cache directory
        run: |
          if [ ! -d /var/cache/apt/archives ]; then
            sudo mkdir -p /var/cache/apt/archives
          fi
          sudo chown -R $USER:$USER /var/cache/apt/archives
          sudo chmod -R 777 /var/cache/apt/archives

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: List cached apt-get packages
        run: ls -la /var/cache/apt/archives

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --tag myapp .

      - name: Run tests
        run: |
          docker run -it --rm -v $PWD:/app myapp pytest
        env:
          PYTHONPATH: /app/src:/app/test
