name: Python CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      PYTHONPATH: ${{github.workspace}}/logbook/logbook/src; ${{github.workspace}}/logbook/logbook/test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest
