on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check cache directory
        run: |
          if [ ! -d /var/cache/apt/archives ]; then
            sudo mkdir -p /var/cache/apt/archives
          fi
          sudo chown -R $USER:$USER /var/cache/apt/archives
          sudo chmod -R 777 /var/cache/apt/archives  

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache apt-get packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install -y libsndfile1 ffmpeg
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=${{github.workspace}}/src:${{github.workspace}}/test
          source .venv/bin/activate
          pytest
