name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      PYTHONPATH: ${{ env.PYTHONPATH }}
    env_file: env.list
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Print PYTHONPATH
      run: echo $PYTHONPATH

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1 ffmpeg
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
